### ISSUE TITLE
https://evercam-static.vercel.app/pricing-list   500 Error

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-static#11]
SHould be https://evercam.io/pricing-list

**Comment by studentofcoding** [comment]
The details are fixed now - https://evercam.sg/pricing-list
<img width="1440" alt="Screenshot 2023-06-06 at 23 06 41" src="https://github.com/evercam/evercam-static/assets/20473526/5eef346a-cdc4-4966-be32-50e6fb498da3">

On another detail, we still have €395 on our past sg site https://test.evercam.sg/pricing-list
<img width="1440" alt="Screenshot 2023-06-06 at 23 06 52" src="https://github.com/evercam/evercam-static/assets/20473526/3be2e8ac-fddf-4f16-a247-c2ede3a651f3">

Do we want to change it to full $ or keep it @marcoherbst

**Comment by marcoherbst** [comment]
The €395 should be S$690

(notice the S before the $, I think that's the correct way to write it)

@affan00 what was there before on the WP site?

**Comment by affan00** [comment]
We have two pages on SG WP site one is linked to the header https://test.evercam.sg/pricing and it is displaying `$690`
![image](https://github.com/evercam/evercam-static/assets/14149453/9480bc2a-d554-4f28-bd64-cfb932bfa75c)

and the second is https://test.evercam.sg/pricing-list (not linked anywhere) and it is displaying `$395`
![image](https://github.com/evercam/evercam-static/assets/14149453/28566168-f3b9-4eed-b8c9-8ff545f81e75)

there is no sign of `S` mentioned on any page. I think it's a typo in https://test.evercam.sg/pricing-list (SG WP site), it should be `$690` instead of `$395`.
we need to update the https://evercam.sg/pricing-list from `$395` to `$690`. 
we can add a note something like `rates are in Singapore dollars` or can add `S` sign with rates.

**Comment by studentofcoding** [comment]
Done it @marcoherbst https://evercam.sg/pricing-list

**Comment by studentofcoding** [comment]
Thanks @affan00
