### ISSUE TITLE
Test Internationalization on staging domains

### ISSUE THREAD

**Issue by yzdbg** [evercam/evercam-static#18]
@studentofcoding @halimb I've added staging domains for `.io`, `.us`, `.au` and `.pl` (uk to be added soon).

https://staging.evercam.io/
https://staging.evercam.com/
https://staging.evercam.uk/
https://staging.evercam.com.au/
https://staging.evercam.pl/

### The current environment configuration in vercel 
```
DOMAIN_SG=https://evercam.sg/
DOMAIN_IE=https://evercam.io/
DOMAIN_US=https://evercam.com/
DOMAIN_UK=https://evercam.uk/
DOMAIN_AU=https://evercam.com.au/
DOMAIN_PL=https://evercam.pl/
```

The configuration should be updated to : 

```
DOMAIN_SG=https://evercam.sg/
DOMAIN_IE=https://staging.evercam.io/
DOMAIN_US=https://staging.evercam.com/
DOMAIN_UK=https://staging.evercam.uk/
DOMAIN_AU=https://staging.evercam.com.au/
DOMAIN_PL=https://staging.evercam.pl/
```

Once that is done, the `@nuxt/i18n` module _should_ automatically change the locale properly depending on the domain.
See : 
https://github.com/evercam/evercam-static/blob/ac10c2571611ec0ba28f3501206b4ba2d516b774/nuxt.config.js#L46-L56

That is not working properly at the moment and should be fixed.

With the `@nuxt/i18n` module properly changing locales based on the domains we can start testing the Internationalization & different domain based content.

**Comment by studentofcoding** [comment]
New information for Preparing Internalization

On Storyblok We can use `Advanced paths` to make the visual editor changes based on Language selection 

Example below

- Use https://www.yoursite.de/ when the language is "de" and otherwise use [https://www.yoursite.com/{{lang}}](https://www.yoursite.com/%7B%7Blang%7D%7D)


`{{if(options.lang == 'de')}}https://www.yoursite.de/{{#else}}https://www.yoursite.com/{{lang}}{{/if}}`

What we need is to upgrade to `Teams` plans so we can try using these with Field Level Translation
<img width="1440" alt="Screenshot 2023-06-06 at 14 34 14" src="https://github.com/evercam/evercam-static/assets/20473526/b6430370-d937-473a-81f1-7108762662bd">

**Comment by studentofcoding** [comment]
Hey guys, so there were 2 updates on multi-domain

- On Storyblok, after using the Advanced Paths visual editor can change based on the language we select, But Big Problem arises because we have to give Real Path to every post & page we have (and we already have more than > 400 pages). Therefore I revert to the default state, and waiting for the response from the Storyblok representative on this. My thought on this is Storyblok can only use Folder-level translation for our needs, but let's see

- On code, I found a solution that finally makes our Multi-domain works on staging, https://staging.evercam.io/ (en-IE) & https://staging.evercam.com.au/ (en-AU), The thing is, it needs a personal branch for each language. I've also opened an issue on i18n about these here https://github.com/nuxt-modules/i18n/issues/2140 let's see what they shared with us

**Comment by studentofcoding** [comment]
5 out of 6 corresponding url are online and can be selected on Storyblok now
- https://staging.evercam.io/
- https://staging.evercam.sg/
- https://staging.evercam.uk/
- https://staging.evercam.com.au/
- https://staging.evercam.com/
- https://staging.evercam.pl/ (Needs checking)

TODO
- Check if the component can be updated in each language
- Check if content can be updated in each language
- Configure Realpath
